### ISSUE TITLE
313쪽 1분 퀴즈 문제에 주어진 조건과 해설상의 문제풀이 내용이 불일치하는 듯 합니다.

### ISSUE THREAD

**Issue by hoony0203** [ZeroCho/es2021-webgame#11]
6월 25일 초판 기준으로 p313 1분퀴즈의 선지는

2021년 2월 21일과 2021년 3월 3일은 며칠 차이가 날까요? 라고 되어 있습니다.

 이에 대한 제 풀이는 아래와 같고

        const date1 = new Date(2021, 2, 21);

        const date2 = new Date(2021, 3, 3);

        const dateDiff = (date2-date1)/1000/60/60/24;

        console.log("dateDiff : " + dateDiff);`

이렇게 하면 13일이 나오고

해설상에는

const diff = new Date(2021, 2, 3) - new Date(2021, 1, 21);

console.log(diff / 1000/ 60 / 60 /24);

로 답이 10으로 나와있습니다.

어느 것이 맞는지, 
혹여 제가 놓친 부분이 있어서 혼동하는 것이라면 짚어주셨으면 합니다. 감사합니다.

**Comment by hoony0203** [comment]
자체 해결하였습니다. 

date 함수는 월에 +1을 해야하는군요!

**Comment by ZeroCho** [comment]
사람이 사용하는 월에 -1 입니다!

**Comment by hoony0203** [comment]
> 사람이 사용하는 월에 -1 입니다!

넵 감사합니다
