### ISSUE TITLE
354페이지 쿼테이션을 백틱으로 고쳐야할듯 합니다

### ISSUE THREAD

**Issue by hoony0203** [ZeroCho/es2021-webgame#12]
$heroLevel.textContent = '${hero.lev}Lev';
                $heroHp.textContent = 'HP : ${hero.hp}/${hero.maxHp}';
                $heroXp.textContent = 'XP : ${hero.xp}/${15*hero.lev}';
                $heroAtt.textContent = 'ATT : ${hero.att}';
                hero.name = name;

비슷해서 눈에 잘 띄지는 않는데 책 내용상에는 
각도가 기울여지지 않은 작은 따옴표로 되어 있습니다.

따옴표로 해도 되는 부분이라면 알려주세요.

**Comment by ZeroCho** [comment]
감사합니다. 백틱으로 해야합니다.

**Comment by hoony0203** [comment]
> 감사합니다. 백틱으로 해야합니다.

답변 감사합니다!

**Comment by ZeroCho** [comment]
다음 인쇄 때 수정해야 해서 open으로 남겨두겠습니다.

**Comment by hoony0203** [comment]
넵 ^^
